services:
  - type: web
    name: flask-quiz-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python admin_dashboard.py"
    envVars:
      - key: PORT
        value: 10000
